Added download file method to virtual machine
jossef/vmwc pull request #5
Opened 2017-06-23 07:06 UTC by Steven17D

2017-06-30 07:10 UTC, jossef requested changes
:1st_place_medal:

2017-06-30 07:10 UTC, jossef commented on vmwc/__init__.py
> +            for chunk in resp.iter_content(chunk_size=1024):
the `1024` can be placed as an optional parameter so the user may change it when required;

```
def download_file(self, guest_path, local_path, chunk_size=1024)
```

2017-06-30 07:10 UTC, jossef commented on vmwc/__init__.py
> +        resp = requests.get(fti.url.replace("https://*", "https://" + self._client.host), verify=False)
you can use `self._client.verify` to determine if SSL verification is required in this session

2017-06-30 07:10 UTC, jossef commented on examples/virtual-machine-download-file.py
> +    main()
great example, add it to the `README.md` file as well 
😉

2017-07-08 06:54 UTC, Steven17D commented
Hi Jossef, I fixed all the notes that you gave me.

2017-07-22 17:35 UTC, jossef approved these changes

2017-07-22 17:35 UTC, merged